# SITE SETTINGS
title: Wild Album
description: Discover camera trap data for research and conservation.
url: "https://camera-trap.hp.gbif.org/"
baseurl: "" # Start with slash if used


# SOCIAL PROFILES
email: info@gbif.org
github_username: gbif/hp-camera-trap

# THEME SETTINGS
algae:
  rootLang: en
  # logo: /assets/images/fungi.svg # Displayed with 28px height
  # logoAndTitle: false
  archive_permalink: /news/
  latestPostLimit: 2
  style:
    square: false
    colors:
      primary: "#0587be"          # Primary color. WILDLABS blue
      links: "#ec7823"            # Link color (defaults to primary). WILDLABS orange
    coloredHeadlineLinks: false   # If a headline is a link, then use the link color. Default is true. 
  navbar:                         # RELATED TO NAVIGATION BAR
    # brandBackground: yellow     # Define a custom background for the logo/title in the top navigation bar
    # color: "tomato"             # What color should the navbar be?
    # hasWhiteText: true          # Should the text color be white?
    # floating: true

useSharedLibrary: true # Use the new component library
updateTranslationMenuOnWidgetEvents: true
permalink: pretty # Will strip extensions like .html from urls

# BUILD SETTINGS
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: gbif/jekyll-hp-base-theme
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .LICENSE
  - .netlify.toml
  - .README.md
  - serve.json

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: "" # All files in the project
    values:
      layout: "page"
      lang: en
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "/news/:year/:slug/"
